import { supabase } from '@/lib/supabase';
import * as ImagePicker from 'expo-image-picker';

// ─── Auth ────────────────────────────────────────────────────────────────────

/**
 * Returns the current session user. If none exists, signs in anonymously.
 * All routine writes require a user_id for RLS enforcement.
 */
export async function getOrCreateUser() {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.user) {
    throw new Error('User not authenticated. Please sign in.');
  }
  return session.user;
}

// ─── Image Upload ─────────────────────────────────────────────────────────────

/**
 * Uploads a local image URI to Supabase Storage.
 * Returns the public URL of the uploaded image.
 * @param localUri  - Local file URI from ImagePicker
 * @param userId    - Owner's user ID
 * @param routineId - Routine's UUID
 * @param path      - 'cover' | 'products/1' | 'products/2' etc.
 */
export async function uploadRoutineImage(
  localUri: string,
  userId: string,
  routineId: string,
  path: string
): Promise<string> {
  const ext = localUri.split('.').pop()?.toLowerCase() || 'jpg';
  const mimeType = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
  const storagePath = `${userId}/${routineId}/${path}.${ext}`;

  const response = await fetch(localUri);
  const blob = await response.blob();

  const { error } = await supabase.storage
    .from('routine-media')
    .upload(storagePath, blob, {
      contentType: mimeType,
      upsert: true,
    });

  if (error) throw error;

  const { data } = supabase.storage
    .from('routine-media')
    .getPublicUrl(storagePath);

  return data.publicUrl;
}

// ─── Routines CRUD ────────────────────────────────────────────────────────────

/**
 * Fetches all routines for the current user, sorted newest first.
 */
export async function fetchRoutines() {
  const user = await getOrCreateUser();

  const { data, error } = await supabase
    .from('routines')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false });

  if (error) throw error;
  return data ?? [];
}

/**
 * Fetches a single routine by ID.
 */
export async function fetchRoutineById(id: string) {
  const { data, error } = await supabase
    .from('routines')
    .select('*')
    .eq('id', id)
    .single();

  if (error) throw error;
  return data;
}

/**
 * Creates a new routine. Uploads cover/product images to Storage first.
 * share_code is auto-generated by Postgres function — DO NOT pass it.
 */
export async function createRoutine(params: {
  title: string;
  coverImageUri?: string;
  stepData: Record<number, any>;
}) {
  const user = await getOrCreateUser();

  // 1. Insert routine first to get the UUID (needed for storage path)
  const { data: inserted, error: insertError } = await supabase
    .from('routines')
    .insert({
      user_id: user.id,
      title: params.title,
      steps_count: Object.keys(params.stepData).length,
      step_data: params.stepData,
    })
    .select()
    .single();

  if (insertError) throw insertError;

  const routineId = inserted.id;
  let coverImageUrl = inserted.cover_image_url;
  let updatedStepData = { ...params.stepData };
  let needsUpdate = false;

  // 2. Upload cover image if local URI
  if (params.coverImageUri && params.coverImageUri.startsWith('file://')) {
    coverImageUrl = await uploadRoutineImage(
      params.coverImageUri, user.id, routineId, 'cover'
    );
    needsUpdate = true;
  } else if (params.coverImageUri) {
    coverImageUrl = params.coverImageUri;
    needsUpdate = true;
  }

  // 3. Upload product images in steps if local URIs
  for (const key of Object.keys(updatedStepData)) {
    const step = updatedStepData[Number(key)];
    if (step?.productImage && step.productImage.startsWith('file://')) {
      const url = await uploadRoutineImage(
        step.productImage, user.id, routineId, `products/${key}`
      );
      updatedStepData[Number(key)] = { ...step, productImage: url };
      needsUpdate = true;
    }
  }

  // 4. Update with resolved image URLs
  if (needsUpdate) {
    const { data: updated, error: updateError } = await supabase
      .from('routines')
      .update({
        cover_image_url: coverImageUrl,
        step_data: updatedStepData,
      })
      .eq('id', routineId)
      .select()
      .single();

    if (updateError) throw updateError;
    return updated;
  }

  return inserted;
}

/**
 * Updates an existing routine. Uploads any new local images first.
 */
export async function updateRoutine(
  routineId: string,
  params: {
    title: string;
    coverImageUri?: string;
    stepData: Record<number, any>;
  }
) {
  const user = await getOrCreateUser();

  let coverImageUrl: string | undefined = params.coverImageUri;
  let updatedStepData = { ...params.stepData };

  // Upload cover if new local URI
  if (params.coverImageUri && params.coverImageUri.startsWith('file://')) {
    coverImageUrl = await uploadRoutineImage(
      params.coverImageUri, user.id, routineId, 'cover'
    );
  }

  // Upload new product images
  for (const key of Object.keys(updatedStepData)) {
    const step = updatedStepData[Number(key)];
    if (step?.productImage && step.productImage.startsWith('file://')) {
      const url = await uploadRoutineImage(
        step.productImage, user.id, routineId, `products/${key}`
      );
      updatedStepData[Number(key)] = { ...step, productImage: url };
    }
  }

  const { data, error } = await supabase
    .from('routines')
    .update({
      title: params.title,
      cover_image_url: coverImageUrl,
      steps_count: Object.keys(updatedStepData).length,
      step_data: updatedStepData,
    })
    .eq('id', routineId)
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Deletes a routine and all its associated storage files.
 */
export async function deleteRoutine(routineId: string) {
  const user = await getOrCreateUser();

  // Delete storage files for this routine
  const { data: files } = await supabase.storage
    .from('routine-media')
    .list(`${user.id}/${routineId}`);

  if (files && files.length > 0) {
    const paths = files.map((f) => `${user.id}/${routineId}/${f.name}`);
    await supabase.storage.from('routine-media').remove(paths);
  }

  const { error } = await supabase
    .from('routines')
    .delete()
    .eq('id', routineId);

  if (error) throw error;
}

/**
 * Maps a Supabase routine row back to the shape the app components expect.
 */
export function mapSupabaseRoutine(row: any) {
  return {
    id: row.id,
    title: row.title,
    coverImage: row.cover_image_url ?? '',
    stepsCount: row.steps_count,
    stepData: row.step_data ?? {},
    shareCode: row.share_code,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}
