// Shared mock scans data — used by scan history page and select-scans picker
export const MOCK_SCANS = [
  {
    id: '1',
    date: 'Today',
    timestamp: new Date().getTime(),
    score: 85,
    skinType: 'Normal',
    image: require('../../assets/images/after_skin.png'),
    status: 'Healthy & Glowing',
  },
  {
    id: '2',
    date: 'Jul 28, 2026',
    timestamp: new Date('2026-07-28').getTime(),
    score: 81,
    skinType: 'Combination',
    image: require('../../assets/images/before_skin.png'),
    status: 'Mild Redness',
  },
  {
    id: '3',
    date: 'Jul 15, 2026',
    timestamp: new Date('2026-07-15').getTime(),
    score: 78,
    skinType: 'Dry',
    image: require('../../assets/images/after_skin.png'),
    status: 'Dry Patches',
  },
  {
    id: '4',
    date: 'Jul 01, 2026',
    timestamp: new Date('2026-07-01').getTime(),
    score: 75,
    skinType: 'Oily',
    image: require('../../assets/images/before_skin.png'),
    status: 'Moderate Acne',
  },
  {
    id: '5',
    date: 'Jun 20, 2026',
    timestamp: new Date('2026-06-20').getTime(),
    score: 72,
    skinType: 'Sensitive',
    image: require('../../assets/images/after_skin.png'),
    status: 'High Redness',
  },
  {
    id: '6',
    date: 'May 10, 2026',
    timestamp: new Date('2026-05-10').getTime(),
    score: 70,
    skinType: 'Combination',
    image: require('../../assets/images/before_skin.png'),
    status: 'Pore Congestion',
  },
  {
    id: '7',
    date: 'Aug 14, 2026',
    timestamp: new Date('2026-08-14').getTime(),
    score: 86,
    skinType: 'Normal',
    image: require('../../assets/images/after_skin.png'),
    status: 'Clear & Radiant',
  },
  {
    id: '8',
    date: 'Aug 10, 2026',
    timestamp: new Date('2026-08-10').getTime(),
    score: 83,
    skinType: 'Combination',
    image: require('../../assets/images/before_skin.png'),
    status: 'Hydrated Tone',
  },
  {
    id: '9',
    date: 'Aug 02, 2026',
    timestamp: new Date('2026-08-02').getTime(),
    score: 80,
    skinType: 'Oily',
    image: require('../../assets/images/after_skin.png'),
    status: 'Slight Oiliness',
  },
  {
    id: '10',
    date: 'Jul 22, 2026',
    timestamp: new Date('2026-07-22').getTime(),
    score: 79,
    skinType: 'Dry',
    image: require('../../assets/images/before_skin.png'),
    status: 'Mild Flakiness',
  },
  {
    id: '11',
    date: 'Jul 08, 2026',
    timestamp: new Date('2026-07-08').getTime(),
    score: 77,
    skinType: 'Sensitive',
    image: require('../../assets/images/after_skin.png'),
    status: 'Calm Skin Barrier',
  },
  {
    id: '12',
    date: 'Jun 28, 2026',
    timestamp: new Date('2026-06-28').getTime(),
    score: 74,
    skinType: 'Normal',
    image: require('../../assets/images/before_skin.png'),
    status: 'Smooth Texture',
  },
  {
    id: '13',
    date: 'Jun 12, 2026',
    timestamp: new Date('2026-06-12').getTime(),
    score: 73,
    skinType: 'Combination',
    image: require('../../assets/images/after_skin.png'),
    status: 'Balanced T-Zone',
  },
  {
    id: '14',
    date: 'May 25, 2026',
    timestamp: new Date('2026-05-25').getTime(),
    score: 71,
    skinType: 'Oily',
    image: require('../../assets/images/before_skin.png'),
    status: 'Minor Breakouts',
  },
  {
    id: '15',
    date: 'Apr 18, 2026',
    timestamp: new Date('2026-04-18').getTime(),
    score: 68,
    skinType: 'Sensitive',
    image: require('../../assets/images/after_skin.png'),
    status: 'Mild Irritation',
  },
  {
    id: '16',
    date: 'Mar 05, 2026',
    timestamp: new Date('2026-03-05').getTime(),
    score: 65,
    skinType: 'Dry',
    image: require('../../assets/images/before_skin.png'),
    status: 'Dehydrated Texture',
  },
];

export type ScanItem = typeof MOCK_SCANS[number];
