import React from 'react';
import { View, StyleSheet, ScrollView, Pressable, Platform } from 'react-native';
import { Text } from '@/components/AppText';
import { useRouter } from 'expo-router';
import { useColorScheme } from '@/hooks/use-color-scheme';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ChevronLeft, FileText, AlertTriangle } from 'lucide-react-native';

export default function TermsOfServiceScreen() {
  const router = useRouter();
  const scheme = useColorScheme();
  const isDark = scheme === 'dark';
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.root, isDark ? styles.bgDark : styles.bgLight, { paddingTop: insets.top }]}>
      {/* Clean Top Back Chevron (non-bordered, fixed top) */}
      <View style={styles.topHeader}>
        <Pressable onPress={() => router.back()} style={styles.backBtn} hitSlop={15}>
          <ChevronLeft size={26} color={isDark ? '#ffffff' : '#111827'} strokeWidth={2.4} />
        </Pressable>
      </View>

      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 20 }]}
        showsVerticalScrollIndicator={false}
      >
        {/* Neutral Hero Icon */}
        <View style={[styles.iconHero, isDark ? styles.iconHeroDark : styles.iconHeroLight]}>
          <FileText size={36} color={isDark ? '#ffffff' : '#111827'} strokeWidth={2.2} />
        </View>

        <Text style={[styles.title, isDark ? styles.textDark : styles.textLight]}>
          Terms of Service
        </Text>
        <Text style={[styles.lastUpdated, isDark ? styles.subtextDark : styles.subtextLight]}>
          Effective Date: August 18, 2026
        </Text>

        {/* Medical Notice Box */}
        <View style={[styles.summaryCard, isDark ? styles.cardDark : styles.cardLight]}>
          <AlertTriangle size={20} color={isDark ? '#fbbf24' : '#d97706'} style={{ marginTop: 2 }} />
          <Text style={[styles.summaryText, isDark ? styles.textDark : styles.textLight]}>
            <Text style={{ fontWeight: '700' }}>Important Notice:</Text> Skin Story provides AI-assisted skincare tracking and informational analysis. It is not a medical device and does not provide medical, dermatological, or clinical diagnosis.
          </Text>
        </View>

        {/* Section 1 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            1. Acceptance of Terms
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            By downloading, accessing, or using Skin Story ("the Application"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all terms and conditions, you must refrain from using the Application.
          </Text>
        </View>

        {/* Section 2 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            2. Informational & Skincare Disclaimer
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            The skin scores, routine suggestions, dos and don'ts, and progress analytics generated by Skin Story are for general wellness and educational tracking only. They should never be interpreted as clinical diagnoses or medical treatment plans. Always consult a licensed board-certified dermatologist or healthcare professional for acute skin conditions, severe acne, or allergic reactions.
          </Text>
        </View>

        {/* Section 3 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            3. Eligibility & User Accounts
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            You must be at least 13 years of age (or 16 in the European Economic Area) to use Skin Story. You are responsible for safeguarding your device, maintaining accurate profile details, and controlling access to your account data.
          </Text>
        </View>

        {/* Section 4 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            4. User-Generated Content & Public Routines
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            You retain ownership of the custom routines, product steps, photos, and notes you input into the app. When creating or sharing public routines:
          </Text>
          <Text style={[styles.bulletBody, isDark ? styles.subtextDark : styles.subtextLight]}>
            • You agree not to upload harmful, offensive, defamatory, or copyright-infringing content.
          </Text>
          <Text style={[styles.bulletBody, isDark ? styles.subtextDark : styles.subtextLight]}>
            • You grant Skin Story a non-exclusive, royalty-free license to display and distribute anonymous public routines to other community members.
          </Text>
        </View>

        {/* Section 5 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            5. Intellectual Property
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            All trademarks, logos, visual layouts, animations, algorithms, and software comprising Skin Story are the exclusive intellectual property of Skin Story and its licensors. You may not copy, modify, distribute, reverse-engineer, or decompile any part of the Application.
          </Text>
        </View>

        {/* Section 6 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            6. Limitation of Liability
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            To the maximum extent permitted by applicable law, Skin Story and its developers shall not be liable for any indirect, incidental, punitive, or consequential damages resulting from your use of the Application, reliance on any skin score recommendations, or third-party cosmetic product applications.
          </Text>
        </View>

        {/* Section 7 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            7. Termination & Account Deletion
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            You may terminate this agreement at any time by deleting your account via <Text style={{ fontWeight: '700' }}>Profile → Delete Account</Text> and uninstalling the Application. We reserve the right to suspend or terminate access for violations of these Terms.
          </Text>
        </View>

        {/* Section 8 */}
        <View style={styles.section}>
          <Text style={[styles.sectionHeading, isDark ? styles.textDark : styles.textLight]}>
            8. Changes to Terms
          </Text>
          <Text style={[styles.paragraph, isDark ? styles.subtextDark : styles.subtextLight]}>
            We reserve the right to modify these Terms at any time. Continued use of the Application following any updates signifies your agreement to the revised Terms.
          </Text>
        </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  bgLight: { backgroundColor: '#FAF8F6' },
  bgDark: { backgroundColor: '#121212' },
  topHeader: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 4,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  iconHero: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 14,
    marginTop: 4,
  },
  iconHeroLight: {
    backgroundColor: '#f3f4f6',
  },
  iconHeroDark: {
    backgroundColor: '#27272a',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 4,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  lastUpdated: {
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Outfit_400Regular',
  },
  summaryCard: {
    flexDirection: 'row',
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  summaryText: {
    flex: 1,
    fontSize: 13.5,
    lineHeight: 20,
    fontWeight: '500',
    fontFamily: 'Outfit_500Medium',
  },
  cardLight: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e7eb',
  },
  cardDark: {
    backgroundColor: '#1c1c1e',
    borderColor: '#27272a',
  },
  section: {
    marginBottom: 22,
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    fontFamily: 'Outfit_700Bold',
    letterSpacing: -0.2,
  },
  paragraph: {
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Outfit_400Regular',
    marginBottom: 6,
  },
  bulletBody: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Outfit_400Regular',
    marginBottom: 6,
    paddingLeft: 4,
  },
  textLight: { color: '#111827' },
  textDark: { color: '#ffffff' },
  subtextLight: { color: '#4b5563' },
  subtextDark: { color: '#a1a1aa' },
});
